import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { LayoutDashboard, Mail, Terminal, MessageSquare, AlertCircle, Settings } from "lucide-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "On-Call Practice Platform",
  description: "Practice debugging applications generated by AI.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-50 text-gray-900 h-screen flex overflow-hidden`}>
        {/* Sidebar */}
        <aside className="w-64 bg-white border-r border-gray-200 flex flex-col">
          <div className="p-6 border-b border-gray-200 flex items-center gap-2">
            <AlertCircle className="text-red-500" />
            <h1 className="text-xl font-bold text-gray-800">On-Call Sim</h1>
          </div>
          <nav className="flex-1 p-4 space-y-2">
            <Link href="/" className="flex items-center gap-3 px-4 py-3 text-gray-700 rounded-lg hover:bg-gray-100 transition-colors">
              <LayoutDashboard size={20} />
              <span className="font-medium">Dashboard</span>
            </Link>
            <Link href="/email" className="flex items-center gap-3 px-4 py-3 text-gray-700 rounded-lg hover:bg-gray-100 transition-colors">
              <Mail size={20} />
              <span className="font-medium">Inbox</span>
            </Link>
            <Link href="/console" className="flex items-center gap-3 px-4 py-3 text-gray-700 rounded-lg hover:bg-gray-100 transition-colors">
              <Terminal size={20} />
              <span className="font-medium">Cloud Console</span>
            </Link>
            <Link href="/chat" className="flex items-center gap-3 px-4 py-3 text-gray-700 rounded-lg hover:bg-gray-100 transition-colors">
              <MessageSquare size={20} />
              <span className="font-medium">AI Assistant</span>
            </Link>
            <Link href="/settings" className="flex items-center gap-3 px-4 py-3 text-gray-700 rounded-lg hover:bg-gray-100 transition-colors">
              <Settings size={20} />
              <span className="font-medium">Settings</span>
            </Link>
          </nav>
          <div className="p-4 border-t border-gray-200 text-xs text-gray-500 text-center">
            Powered by Gemini
          </div>
        </aside>

        {/* Main Content */}
        <main className="flex-1 flex flex-col overflow-hidden">
          {children}
        </main>
      </body>
    </html>
  );
}